#!/bin/bash
#SBATCH -A CS4380_CS5351 # account name
#SBATCH -J p5_tsp        # job name
#SBATCH -o p5_tsp.%j     # name of the output and error file
#SBATCH -N 1             # total number of nodes requested
#SBATCH -n 1             # total number of tasks requested
#SBATCH -p gpu           # queue name
#SBATCH -t 00:01:00      # expected maximum runtime (hh:mm:ss)

./tsp_cuda /home1/00976/burtsche/Parallel/d1291.btsp
./tsp_cuda /home1/00976/burtsche/Parallel/d1291.btsp
./tsp_cuda /home1/00976/burtsche/Parallel/d1291.btsp

./tsp_cuda /home1/00976/burtsche/Parallel/nrw1379.btsp
./tsp_cuda /home1/00976/burtsche/Parallel/nrw1379.btsp
./tsp_cuda /home1/00976/burtsche/Parallel/nrw1379.btsp

./tsp_cuda /home1/00976/burtsche/Parallel/fl1400.btsp
./tsp_cuda /home1/00976/burtsche/Parallel/fl1400.btsp
./tsp_cuda /home1/00976/burtsche/Parallel/fl1400.btsp

date

